version: "3"
services:
  squidproxy01:
    image: "ubuntu/squid"
    command: ""
    extra_hosts:
    - "squidproxy01:127.0.0.1"
    ports:
    - "3128:3128"
    network_mode: host
    volumes: 
      - ./squid.conf:/etc/squid/squid.conf
      - ./passwd:/etc/squid/passwd

  squidproxy02:
    image: "ubuntu/squid"
    command: ""
    extra_hosts:
    - "squidproxy02:127.0.0.1"
    ports:
    - "3128:3128"
    network_mode: host
    volumes: 
      - ./squid.conf:/etc/squid/squid.conf
      - ./passwd:/etc/squid/passwd

  sauce-connect:
    image: "saucelabs/sauce-connect:5.0"
    environment:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      PROXY_PASSWD: ${PROXY_PASSWD}
      SAUCE_OUTPUT_FORMAT: "text"
    command: "run -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -c /opt/sauce-connect.yaml --auth proxyuser:$PROXY_PASSWD@squidproxy01:3128 --auth proxyuser:$PROXY_PASSWD@squidproxy02:3128"
    network_mode: host
    volumes: 
      - ./sauce-connect.yaml:/opt/sauce-connect.yaml
    
